name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy_prod:
    name: "Deploy Databricks Bundle"
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI and Bundle
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh 
          pip install wheel
        shell: bash

      - name: Validate Databricks Bundle
        run: |
          echo "Starting Databricks Validation..."
          databricks bundle validate -t prod
        env:
          DATABRICKS_HOST: 'https://adb-2341468374037462.2.azuredatabricks.net'
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID_PROD }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET_PROD }}
          DATABRICKS_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID_PROD }}
          DATABRICKS_BUNDLE_ENV: prod
          DATABRICKS_AUTH_TYPE: oauth

      - name: Deploy Databricks Bundle
        run: |
          echo "Starting Databricks Deployment..."
          databricks bundle deploy -t prod
        env:
          DATABRICKS_HOST: 'https://adb-2341468374037462.2.azuredatabricks.net'
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID_PROD }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET_PROD }}
          DATABRICKS_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID_PROD }}
          DATABRICKS_BUNDLE_ENV: prod
          DATABRICKS_AUTH_TYPE: oauth
